name: minions-portfolio-manager-workspace
project_scope: main
project_type: monorepo
description: "Agent to manage global hierarchies, ecosystems, and projects"
tier: idea
lane: minions
priority: medium
oss: true
stack: [typescript]
repo: "https://github.com/mxn2020/minions-portfolio-manager"
deploy_url: null
last_active: 2026-02-25
tags: [minion, toolbox, ai-agent, automation, minions, portfolio, manager]
notes: null
id: fa9922f0-7ae7-400c-b879-4e5933d5c4ff
